### ISSUE TITLE
Run Lossless Image Compression

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/tutorial#1]
- [ ] @ZjelcoP ready for optiPng to be run 
- [ ] @triplea-maps/mapadmins run optiPng and update repository files

OptiPng is a lossless image compression tool we can run on the PNG image files. @ZjelcoP , check the box above when you're ready for optiPng to be run.

**Comment by ZjelcoP** [comment]
okay thx. I will be altering and adding some images in the future.
Wise to wait with this then?

**Comment by DanVanAtta** [comment]
yip, just check the first box when you're done / ready

**Comment by DanVanAtta** [comment]
Let's worry about this when the map is going to be released.

**Comment by ZjelcoP** [comment]
All png's seem to have been changed. Was optipng run?
They're back to original now.

Can this step be done by the Builderbot? So just the releaseversions are optimized.
For development I'd like to keep original imagefiles. Not sure what optipng does to compress it, but could it hamper editing of these images after compression? (zoom in, zoom out, colors, whatever)

**Comment by DanVanAtta** [comment]
Either it was the addition of Git LFS (which broke things, I've pulled that out since), or it was optipng that updated files.

OptiPng is a lossless compression tool, you lose no color values. PNG stores colors in a color palette that is defined by a few parameters that go into the PNG compression.

OptiPNG plays around with those parameters looking for values that have smaller color pallettes, but still contain every color that is used in the original image. So essentially it just drops the _extra_ color information.

There are lossless compression tools, such as "SmushIt" that work on PNG files. For those I would have them be done by the build process.

Optipng _can_ have errors, but so far over the entire tripleaA map project, there is only one repository actually seeing those issues. Thus the desire to run optiPNG on a periodic basis by hand and not on in an automated way (or at least just yet).

Does that answer the question(s)?

**Comment by ZjelcoP** [comment]
Is Smushit or OptiPng easy to use and on an entire folder? In other words: can I do it myself for the complete map on my own computer.

I prefer to keep one way traffic with Git. I make changes and push those. Other way around I lose track of what is going on. (all new to me)

**Comment by DanVanAtta** [comment]
OptiPNG homepage: http://optipng.sourceforge.net/ 
There is a windows download there.. I haven't had a chance to look at it more from a windows point of view. Let me know if you can run it on full folders easily.

SmushIt loses some image quality during compression. I don't know enough about it yet to run it in bulk (or at all yet).

Git can auto-magically handle a lot of merge conflict updates and learning how to handle a two way flow is useful. For example, you'll be able to work on multiple computers more easily and pushing your local work to another machine is good for backups. Generally it's a best practice to start clean, update local, make a small change and push, and repeat.

Happily it doesn't take too much learning to get over this next step, I recommend taking an hour. To play around with doing updates, create a fork, clone it into two folders, and then you can push from one and update the other.

**Comment by ZjelcoP** [comment]
Can't seem to run optipng either. Should I move it to some folder? Install??

Well it was the Mergeconflicts making me go one-way traffic. No idea what to do with that.
Also the folder I work in is sacred to me. To push I copy it to "work"folder and then commit and push.
This makes two way difficult, I know. But after the program once made changes I didn't want I went for this. Sometimes GIT seems to change things I can't follow.
It's the update local thing that i'm reluctant to use.

Feel like an elderly person with new-tech anxiety, stick with what i know...

**Comment by DanVanAtta** [comment]
I suppose part of the trick is to incrementally learn and remember we all go through the same process. 
Probably more important than learning how to do updates would be first to do a diff of your local work versus the repository, so you know exactly what you are pushing. Helps avoid a lot of mistakes and pushing unintended content.

Merge conflicts are actually not that hard to solve. Open "bash for git", run `git mergetool`, it'll tell you how you can specify a merge tool program. From there you need to get one, opendiff, meld, beyondcompare are some decent merge tools. Once you have the mergetool set, run `git mergetool` again, and you'll be shown 3 files. One is your local, another is the repository, the third is the result. Use the tool to make all three files look the same, generally a matter of clicking some arrows to move stuff left and right.

Though, one step at a time, so doing self-diffs and viewing git history are probably better first steps. One thing we can do in the meantime. If you have a clean slate, then updating should always just work. Meaning, if you push everything, you'll have a clean slate, in which case I can push stuff which you should be able to easily pick up. So we can coordinate like that perhaps for a bit while the process is becoming more mature.

**Comment by DanVanAtta** [comment]
For now I supposed don't worry about running optiPng, we'll coordinate so it is run after you push changes, and we'll also make sure it gets done eventually before the map is launched.
