### ISSUE TITLE
Out of date AI speed setting

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/tutorial#12]
this is out of date, the setting is on the AI tab of the settings window

```
<center><b>AI Speed Setting</b></center><br>
<ul>
        <li>Go to the <b><em>Game-</em></b>tab</li>
        <li>Select <b><em>AI Pause Duration</em></b></li>
        <li>Set to 50ms for fastest moving AI</li>
        <li>Set to 1000ms or more for slow moving AI</li>
        <li>This doesn't change the speed of AI-thinking!</li>
```

**Comment by DanVanAtta** [comment]
https://github.com/triplea-maps/tutorial/pull/13 removed the above text

**Comment by ZjelcoP** [comment]
So the setting has been moved and altered a bit right?
Then I'll just update the info as this was a special request to put it in.
Also there's a notification on this that I will alter.

**Comment by DanVanAtta** [comment]
The setting is still there, but now no longer in the menu bar but instead has moved to the settings window. The AI setting option will also now have a description next to it, hopefully making it is less necessary now to describe what it does.

**Comment by ZjelcoP** [comment]
Okay. Kept it in the tutorial and changed all instances (notifications) that were also mentioning it.
The Engine settings-tab is a great improvement. The explanations will be very welcome to many players.
Also did some spelling checking as Roger pointed out there were some errors. Next time I know to just use a spelling checker and not trust my foreign language skills :-) 0.95 is final as far as I'm concerned. Took it for another test-run without any issues. Any other misplaced punctuation marks or minor spelling error will have to stay.
