### ISSUE TITLE
Rename Armour to Tank

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/tutorial#15]
We cannot use the name "armour", please swap it for "tank"

**Comment by DanVanAtta** [comment]
@ZjelcoP woudl you be able to get to this one relatively soon by any chance?

**Comment by ZjelcoP** [comment]
Well i could but i believe this would be a game wide, over almost all maps wide change isn't it?
You really intend to change this in every map featuring armour?
Right now the Tutorial is consistent with every other map out there i believe.

I'd say leave this for the future, after good review and discussion if it really is worth it.
Personally really don't give 2 cents about US vs UK spelling.
And considering the work to do this over all of TripleA I'd give it a definite no.

**Comment by ZjelcoP** [comment]
Ah, now see the gitter message about hasbro.
Had heard of the IPC issue, but armour?? First time I hear about that one.
Also never heard there was any agreement with Hasbro. Can you eloborate on that?
Only thing I found was this thread http://tripleadev.1671093.n2.nabble.com/Changes-without-actully-changing-anything-tp3286962.html

As it is now Armour is still the most widely used term in just about any map we have.

**Comment by DanVanAtta** [comment]
@ZjelcoP , kindly please change it. If it helps, I will try to give you some extra rationale for doing so, but I'm afraid this is a must-do, it is not a discussion.

I think the thread that discussed necessary changes was a bit before the one you referenced. It was spawned when tripleA received the first cease and desist letter. As part of the legal wrangling, at least these three changes were mandated:
- all maps had to be unbundled from the game
- IPC had to be renamed (to PU)
- Armor had to be renamed (to tanks)

So if we introduce the 'armor' term back into the game, we will be backtracking and potentially opening ourselves up to some legal liability. We _must_ not do that. 

The tutorial map being bundled with the game makes it a bit special, since it can no longer be claimed as community content. That makes the bar higher for the tutorial map. The fact that other maps use 'armor' is probably more because nobody ever changed it, almost 10 years later.. and it is something we should try to fix. The term 'armor' was removed and changed throughout the game engine, the tutorial map being bundled, needs to be up to that same standard. 

On the other point, yeah, I don't really care about US vs UK spelling. But the 'amour' term is something that we cannot use in the game engine, tutorial being bundled is considered as part of the game engine.

**Comment by ZjelcoP** [comment]
Ah yes, had a feeling the bundling made that necessary.
Thank you for the explanation. Will make the changes now.

**Comment by ZjelcoP** [comment]
Done, but i'm completely messing up the gitting here. Can't do it by manual changes, also that would be about 20 Commits. Games folder has dissappeared when deleting the XML? Too long since it did it, and then i used to forcepush which seemed not done...
Also see no option to undo any commits, can't find the button for that...

Here's the complete map with all Tanks. perhaps you can get it in straight.
[tutorial.zip](https://github.com/triplea-maps/tutorial/files/391580/tutorial.zip)

Otherwise I'd have to see about getting into git again in two days when I have time.

**Comment by ZjelcoP** [comment]
Okay, I managed to do it myself after creating a mess.
0.117 Has all fixes including Armour to Tank.

**Comment by DanVanAtta** [comment]
Thanks for taking care of this @ZjelcoP
