### ISSUE TITLE
Reference to "Stats" tab should be updated

### ISSUE THREAD

**Issue by tvleavitt** [triplea-maps/tutorial#19]
I am guessing that the references to a "Stats" tab should be to the "Resources" tab instead, as I see no Stats tab in my game?

**Comment by ssoloff** [comment]
Based on the description of this tab in the game notes:

```xml
<center><b>Stats-tab</b></center><br>
<ul>
	<li>Shows players in their fixed turn order</li>
	<li>PUs = Money in the bank</li>
	<li>Production = Total of all territory value owned, a good measure of economic strength</li>
	<li>Units = number of units on the board</li>
	<li>TUV = Total Unit Value, a rough measure of military strength</li>
	<li>In the bottom, the Allies- and Axis-line shows the added stats per Alliance</li>
</ul><br>
</div>
```

I'm going to say it's actually referring to the **Players** tab:

![players-tab](https://user-images.githubusercontent.com/4826349/48362115-efe09a80-e670-11e8-91d7-526ba0ddddb1.png)

Will fix that shortly.
