### ISSUE TITLE
Resized Map Files folder - incorrect location?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/tutorial#2]
The "Resized Map Files" is placed in the "map" folder, this will have it be bundled with the map zip. If you move it out of this folder, say up one directory, then it will no longer be packaged with the map zip. Just want to check that it was intentional to have this folder where it is: http://github.com/triplea-maps/Tutorial/tree/master/map/Resized%20Map%20Files

**Comment by ZjelcoP** [comment]
Indeed, this has no use being there.
Even wonder where it came from...Probably form messing with mapmaker.

**Comment by DanVanAtta** [comment]
cool, let me know if you want me to 'take care' of it. I'll leave it to you otherwise to delete it.

**Comment by ZjelcoP** [comment]
What happened to the TripleA-maps depository? See all maps left.
You moved them somewhere else? Should I move or delete my map as well?
Could just continue on my own depository.

Date: Tue, 6 Oct 2015 17:09:43 -0700

**Comment by DanVanAtta** [comment]
@ZjelcoP The map repos were not fully set up, they were missing the travis configuration. A few dozen were fully set up, and a couple out of the hundred were missing or had unique problems.

Feel free to continue working in the Tutorial repo, I do not intend to touch it. On the plus side, that missing configuration I have now been able to automate. I hope to have all the map repositories back up over the next day. (will probably take 12 hours to reprocess and upload everything once the script is done, and the script might need more time than just today, in which case it'll be Tuesday or Wednesday before the maps are reposted)

**Comment by DanVanAtta** [comment]
@ZjelcoP  to answer your question more directly, I deleted them in order to recreate them cleanly and with the final and cleaned  up migration script. The script is going to be awesome, shoudl serve to both fully  create and update github repositories using only the map zip.

**Comment by ZjelcoP** [comment]
Okay, Thx
