### ISSUE TITLE
Typos in Tutorial.xml

### ISSUE THREAD

**Issue by tvleavitt** [triplea-maps/tutorial#20]
3596: 

> Move the 2 Infantry from Germany to Slovakia Hungary for the attack. Use the Tank to blitz Greater Southern Germany and join the attack in Slovakia Hungary! But wait..<br><br>

Should be "But wait..." (missing final dot if this is intended as an ellipsis "...").

Line 3770: 

> <center><b>Research Technolgy</b></center><br>

Should be "Technology".

There are also some arguable inconsistencies in terms of capitalization ("Sea zone" in one sentence, "sea zone" in others), bullet points that start without capital letters followed by bullet points that start with capital letters. As well as bullet points that end with punctuation, and others that don't, etc.

**Comment by ssoloff** [comment]
@tvleavitt The fixes for this issue and #19 are now available in the latest version of this map.  For now, you'll have to remove the map and re-download it within TripleA to pick up the changes.

Thanks for reporting these types of issues.  We definitely struggle with spelling, grammar, and punctuation throughout the TripleA code and maps, so any such fixes are always welcome.
