### ISSUE TITLE
.travis.yml file needs update to fix build

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/tutorial#4]
@ZjelcoP the `.travis.yml` needs to be updated to fix the build. Please let me know your preference:

Would you like me to attach the new file contents to this issue and let you do the update, would you rather a pull request (PR), or would you rather master be updated directly? For the moment I'll assume the first option, I'm not quite ready just yet to make the updates. (but pretty soon, days)

**Comment by ZjelcoP** [comment]
I'll do the update when you're ready.

**Comment by DanVanAtta** [comment]
Please update the line that starts with "secure: ..." in the file `.travis.yml` to be the following:

```
secure: tTsenBbWqLLbObk/b4EC3nMfli8MT3bfKVcUHnMn664nWIFHfZwBqQHwawrnVdeqPs0bH1IjdbRgX5p1PJ5o+dNfKYH9NOv5ZDf7UQGFi9vkc0SUe/bR4QfPBW2d9JoP5ZI94bVeDYj4r8RiEiAORIhcvg7TFrXsdVS6LJJI+yeYBegemEkmMAB1dHneep6HedCLhee7AaeDpkxw8ZXStPUH9eGgsXhUTFhgq75wartLYEBhfJPWBTXZBn2HyAzW5gXgtvQHOnBUzjDZOxTkEH8TGRf9D7CgtLuQnsHbNcliQyL0dEcQCB1acGB9LbxW8RYaZqzNnjleQ1c8Qdv+V/x1zn7TfuqzLm7QWrZVvCNL1AHK/1jPgyH9Djvy791tvAVj8ImtiuKBcUGWPHdERR47WWvBfigbNmOJ/hgAUzQDa+YMLp2TDQb0Q8Q9h0O/qpfRyHg2kwCA4sAz9Kc4HaQ7OUFIThqgBHKBV5+/KL/jAOZTqzC2wKQAIA5B0mj3PHAJ6eDwOSb6WpqIoZijQ7qcgN+4cQmfGllOHEx8Q1vboeNkq4cmcFbLL0SFdEXtM/IBl6ZiETMT2/2J6fEy/QVBTG3P/+iH4WRWg2z16ZYSUHmJH45+HEym6xVF/q07sy1Nv5WvWHij9Q/4ad8CgJME4BXTO0mJMxW56TVrzLE=
```

**Comment by ZjelcoP** [comment]
Done
