### ISSUE TITLE
format xml files

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/tutorial#5]
Please run xml lint formatter on the XML -  https://code.google.com/p/xmllint/  

```
start > cmd
cd path_to_tutorial_folder/
xmllint map/games/Tutorial.xml | xmllint > map/games/Tutorial.xml.formatted
  ## now review  map/games/Tutorial.xml.formatted, and make sure things look good before
  ## proceeding with the next step
move map/games/Tutorial.xml.formatted map/games/Tutorial.xml
```

XML lint is a xml formatting tool, it is a second one in addition to optiPNG that will be run in bulk.  Let me know if you have any troubles running it.

**Comment by ZjelcoP** [comment]
What is the use of it? What will it do to the XML-file I can't do myself?

And I have no clue how to use it, program will not open or install.
"XML lint is not recognized as an internal or external command, operable program or batch file"

**Comment by DanVanAtta** [comment]
Formats the XML file, makes it easier to read/understand/catch mistakes. As an alternative to a command line tool, here is an online formatting tool that you can use for XMLs that comes pretty close to the output of  `xmllint`: http://xmlbeautifier.com/.

**Comment by ZjelcoP** [comment]
Well I see little to no difference in the original formatting I was using (ww2 Global written by Veqryn).
It just messes up some parts, especially the parts I temporarily excluded from XML by 

Really don't see any benefit here, unless your writing is very unorganized and messy.
Didn't think mine is....

**Comment by DanVanAtta** [comment]
Some XMLs are in better shape than others. It's a tool that is being run on all map XMLs to make sure the formatting is clean.
