### ISSUE TITLE
Tutorial to tutorial name change cleanup

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/tutorial#6]
In: `map/games/Tutorial.xml`

The map property needs to be updated:

```
-                <property name="mapName" value="Tutorial" editable="false"/>
+                <property name="mapName" value="tutorial" editable="false"/>
```

Also probably would be good to rename Tutorial.xml to be tutorial.xml

@ZjelcoP , would you prefer to take care of this, or I can submit a pull request to make the updates alternatively.

**Comment by ZjelcoP** [comment]
I'll take care of it.

**Comment by ZjelcoP** [comment]
Changed it locally but ran into merge conflicts.
Since I'm working alone on this now and not into solving merge conflicts, I'll upload the map when it's ready for testing. To much work and risks of messing up for no benefit to me that I can see.

Until then if needed you can change anything.
Btw don't understand why you have to change all mapnames, but really dislike it. Looks/feels better with Capitals.

**Comment by DanVanAtta** [comment]
I'm curious where the merge conflict is. Since I haven't changed anything that I know of, I don't know how you ran into one (unless it was there from some time ago already and was just waiting).

It's the repo names that are changing, not necessarily the map names. With so many repos standardization is very important to keeps things under control and automated. For example, some repo's had spaces in their names and that for certain needed to be fixed, but even with that fixed the naming of the map repo's was all over the place.

But ideally our users will never see these map repo names. An ideal user interaction would use the in-game downloader and map selector  and never would be looking at the raw files or repositories where the files are stored. Thus the only name users should really ever see unless they modding the game, will be the in-game map name defined in the XML, which is an arbitrary value (for example pacific.zip has a map name of "Pacific Alpha")

**Comment by DanVanAtta** [comment]
Stale issue at this point, resolving.
