### ISSUE TITLE
Regular map-zip

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-maps/tutorial#8]
The builderbot doesn't automatically build a playable zip-file? 0.46 it somehow did...

**Comment by DanVanAtta** [comment]
For 0.46 I pushed a change to fix a typo in Travis.yml. My guess is the sequence of events was that this change was not picked up, then a force push effectively overwrote it.

At the end of the .travis.yml file there is a typo. Notice it ends with:

```
  on:
    tags: false
    all_branches: tru
```

If you fix the last bit to read (note the 'e' on 'true'):

```
  on:
    tags: false
    all_branches: true
```

Then it should start working again.

**Comment by DanVanAtta** [comment]
PR #9 should fix the problem

**Comment by DanVanAtta** [comment]
Now working again :+1: 
 #10 fixed a second problem, I had a mising  "file: .." line in .travis.yml
